### PR TITLE
feat: link to bridging docs

### PR DESCRIPTION
**Pull request by turadg**
closes: https://github.com/Agoric/agoric-sdk/issues/6453

### CODE REVIEW

**Comment by samsiegart** [comment]
What about a single link that just goes to https://docs.inter.trade/user-how-to/mainnet-only-bridge-external-tokens-to-agoric? It's a bit clunky putting a link on every item especially if it's just for docs instead of the actual bridge site since we're not doing that anymore.
Screen Shot 2022-10-26 at 12 08 11 PM

**Comment by otoole-brendan** [comment]
@samsiegart yes I way prefer this and I think is less overhead/maintenanance overall!

**Review by samsiegart — APPROVED** [review]
Just pushed the single-link version, feel free to merge if code looks good

**Review by turadg — COMMENTED** [review]
LGTM. I can't approve because I made the PR :)  takeitaway @samsiegart .

**Pull request merged**
